name: Flutter Pr

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, X64] 
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable 
          version: 3.10.6
        
      - name: Install dependencies
        run: flutter pub get

      - name: Build in web
        run: flutter build web
  
      - name: Run in web
        run: flutter run -d chrome
    
